name: build-latex

on:
  push:
  pull_request:

jobs:
  validate-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit (lint/format/Makefile tabs)
        run: pre-commit run -a

      - name: Sync figures (make figures)
        run: make figures

      - name: Build LaTeX (latexmk via action)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Main_sr.tex
          working_directory: Manuscripts/Scientific_Reports_v1.6
          latexmk_use_xelatex: false
          latexmk_shell_escape: true
          extra_system_packages: "ghostscript imagemagick"
          continue_on_error: false

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Main_sr.pdf
          path: Manuscripts/Scientific_Reports_v1.6/Main_sr.pdf
          if-no-files-found: error
