---
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - feat
      - feature
      - enhancement
  - title: 'Fixes'
    labels:
      - fix
      - bug
  - title: 'Chore/CI/Docs'
    labels:
      - chore
      - ci
      - docs
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES
