---
exclude: |
  ^(notebooks/|papers/|meta/metadata\.yaml|
    docs/INSTRUCOES_PROJETO\.md|\.github/ISSUE_TEMPLATE/)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.4
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: markdownlint-cli2
        name: markdownlint-cli2
        entry: markdownlint-cli2
        language: node
        types: [markdown]
        additional_dependencies: [markdownlint-cli2@0.11.0]
        args: ["--config", ".markdownlint-cli2.jsonc"]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
