line-length = 88
target-version = "py310"
src = ["src"]
fix = true

extend-exclude = [
  "**/*.ipynb",
]

[lint]
select = ["E", "F"]

[lint.isort]
known-first-party = ["pcs_toolbox"]
combine-as-imports = true
force-single-line = false

[lint.per-file-ignores]
"notebooks/**" = ["E402", "I001", "E501"]
"papers/**" = ["E402", "I001", "E501"]
