---
name: ci-autofix
"on":
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # Executa toda segunda-feira às 9:00 UTC
    - cron: '0 9 * * 1'

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install basic dependencies
        run: |
          pip install ruff black isort
          npm install -g markdownlint-cli2

      - name: Run basic formatting checks
        run: |
          echo "✅ Running basic autofix checks..."
          # Run basic linting (non-breaking)
          ruff check . --fix --exit-zero || true
          echo "✅ Autofix checks completed"

      - name: Generate simple report
        run: |
          mkdir -p reports/
          echo "Autofix run completed at $(date)" > reports/autofix-summary.txt
          echo "✅ Basic autofix completed"

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: autofix-reports
          path: reports/
          retention-days: 7
