---
name: ci-autofix
'on': [push, pull_request]
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install pre-commit
      - run: pre-commit run --all-files || true
      - name: Commit & push auto-fixes (somente em push de branch)
        if: >-
          ${{
            github.event_name == 'push' &&
            startsWith(github.ref, 'refs/heads/')
          }}
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email \
              "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "style(pre-commit): auto-fix formatting"
            git push
          fi
