---
name: ci-python
'on': [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -r requirements.txt || true
      - run: pip install -e src/pcs_toolbox || true
      - run: pip install pre-commit pytest
      - name: Run pre-commit on tracked files
        run: |
          pre-commit run --files $(
            git ls-files '*.py' '*.md' '*.yaml' '*.yml' '*.json' \
              ':!:notebooks/**' ':!:papers/**' \
              ':!:docs/INSTRUCOES_PROJETO.md' ':!:.github/ISSUE_TEMPLATE/**' \
              ':!:meta/metadata.yaml'
          )
      - run: pytest -q
