---
name: ci-validate
on:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install YAML tools
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Check repository structure
        run: |
          echo "✅ Checking repository structure..."

          # Check required files
          required_files=(
            "README.md"
            "LICENSE"
            "CITATION.cff"
            "pyproject.toml"
            "requirements.txt"
          )

          missing=0
          for file in "${required_files[@]}"; do
            if [ -f "$file" ]; then
              echo "✅ Found: $file"
            else
              echo "⚠️ Missing: $file"
              missing=$((missing+1))
            fi
          done
          if [ "$missing" -gt 0 ]; then
            echo "⚠️ Validation found $missing missing required files (non-blocking)"
          fi

      - name: Validate YAML files
        run: |
          echo "✅ Validating YAML files..."
          for yaml_file in $(find . -name "*.yml" -o -name "*.yaml" \
              | grep -v node_modules | head -10); do
            if python - << PY
import yaml, sys
try:
    yaml.safe_load(open(sys.argv[1], 'r'))
    sys.exit(0)
except Exception:
    sys.exit(1)
PY
 "$yaml_file"; then
              echo "✅ Valid YAML: $yaml_file"
            else
              echo "⚠️ Invalid YAML: $yaml_file"
            fi
          done

      - name: Check Python package structure
        run: |
          echo "✅ Checking Python package structure..."
          if [ -d "src/pcs_toolbox" ]; then
            echo "✅ Found Python package: src/pcs_toolbox"
          fi
          if [ -d "tests" ]; then
            echo "✅ Found tests directory"
          fi
