name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (ruff)
        run: |
          ruff --version
          ruff check . || true

      - name: Run unit tests
        run: |
          pytest -q

      - name: Build ZuCo processed data (safe)
        run: |
          python tools/zuco_loader.py || true

      - name: Merge ZuCo + KEC (safe)
        run: |
          python tools/merge_zuco_kec.py || true

      - name: Compute FDR for reading models (safe)
        run: |
          python tools/fdr_reading.py || true

      - name: Validate h* status (safe)
        run: |
          python tools/validate_hstar.py || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-artifacts
          path: |
            reports/**
            figures/metrics/**
            data/processed/**

  r-crosscheck:
    runs-on: ubuntu-latest
    needs: python
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup R 4.3
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'

      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('lme4','broom.mixed','readr','ggplot2'), repos='https://cloud.r-project.org')"

      - name: Run R mixed model cross-check (safe)
        run: |
          Rscript scripts/r_mixedlm_check.R || true

      - name: Upload R reports
        uses: actions/upload-artifact@v4
        with:
          name: r-reports
          path: |
            reports/r_mixedlm_*
