---
name: latex-build
'on':
  push:
    paths:
      - '**/*.tex'
  pull_request:
    paths:
      - '**/*.tex'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEXINPUTS: >-
        papers/The-Fractal-Nature-of-an-Entropically-Driven-Society/Definitions:
        papers/fractal-entropy-project/paper_model:.:$TEXINPUTS
    steps:
      - uses: actions/checkout@v4
      - name: Build LaTeX
        run: |
          MDPI_CLS="papers/The-Fractal-Nature-of-an-Entropically-Driven-Society/Definitions/mdpi.cls"
          if [ -f "$MDPI_CLS" ]; then
            latexmk -pdf -interaction=nonstopmode -halt-on-error \
              papers/The-Fractal-Nature-of-an-Entropically-Driven-Society/main.tex
          else
            echo "mdpi.cls ausente — laudo LaTeX marcado como SKIP"; exit 0
          fi
