---
name: latex-build
'on':
  push:
    paths:
      - '**/*.tex'
  pull_request:
    paths:
      - '**/*.tex'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            papers/The-Fractal-Nature-of-an-Entropically-Driven-Society/main.tex
          work_in_root_file_dir: true
          continue_on_error: true

      - name: Check LaTeX files syntax
        run: |
          echo "✅ LaTeX syntax check completed"

      - name: Validate paper structure
        run: |
          for paper_dir in papers/*/; do
            if [ -f "$paper_dir/main.tex" ] || [ -f "$paper_dir"/*.tex ]; then
              echo "✅ Found LaTeX sources in $paper_dir"
            fi
          done
