---
name: python-tests (manual)
on:
  workflow_dispatch:
jobs:
  test:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install -e . || true
          pip install pytest coverage coverage-badge
      - name: Run tests with coverage
        run: |
          coverage run -m pytest tests/ -v || true
          coverage xml || true
          coverage-badge -o coverage.svg || true
        continue-on-error: true
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.python-version }}
          path: |
            coverage.xml
            coverage.svg
          retention-days: 30
