---
name: python-ci
on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/python.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/python.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .
          pip install pytest ruff black isort
      - name: Run linting
        run: |
          ruff check src/ tests/ --fix || true
          black --check src/ tests/ || true
          isort --check-only src/ tests/ || true
      - name: Run tests
        run: pytest tests/ -v || true
        continue-on-error: true
