name: QA

on:
  push:
  pull_request:

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
      - name: Repo lint
        run: |
          python tools/repo_lint.py
      - name: Markdown linkcheck
        run: |
          python tools/linkcheck_md.py
      - name: Notebook smoke (best-effort)
        run: |
          pip install jupyter nbconvert
          for nb in notebooks/01_swow_loader.ipynb notebooks/03_zuco_loader.ipynb notebooks/02_compute_kec_metrics.ipynb; do
            if [ -f "$nb" ]; then
              jupyter nbconvert --to notebook --execute "$nb" --ExecutePreprocessor.timeout=300 --output /tmp/out.ipynb
            fi
          done
